"""
Django settings for Admin1 project.

Generated by 'django-admin startproject' using Django 3.1.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.1/ref/settings/
"""

from pathlib import Path

import django_heroku
import moneyed
from moneyed.localization import _sign, DEFAULT
# Build paths inside the project like this: BASE_DIR / 'subdir'.
from testtinymce.settings import TINYMCE_DEFAULT_CONFIG

BASE_DIR = Path(__file__).resolve().parent.parent

# Agregado para imagenes
STATIC_URL = '/static/'
STATICFILES_DIRS = [
    django_heroku.os.path.join(BASE_DIR, 'static'),
]
STATIC_ROOT = django_heroku.os.path.join(BASE_DIR, 'static_root')


MEDIA_URL = '/media/'
MEDIA_ROOT = django_heroku.os.path.join(BASE_DIR, 'media')
# Fin Agregado para imagenes

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = '31hm_pxhkrklhldbzch5fjrgvlopgm+%9t^y*u_tv(i&!bdb!g'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = []

# Application definition

LIBRARIES = [
    'djmoney',
    'nested_inline',
    'tinymce',
]

APPS = [
    'LandingPage',
    'Products',
    'Catalog',
]

INSTALLED_APPS = [
                     'django.contrib.admin',
                     'django.contrib.auth',
                     'django.contrib.contenttypes',
                     'django.contrib.sessions',
                     'django.contrib.messages',
                     'django.contrib.staticfiles',
                 ] + LIBRARIES + APPS

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
]

ROOT_URLCONF = 'Admin1.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [BASE_DIR / 'templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'Admin1.wsgi.application'

# Database
# https://docs.djangoproject.com/en/3.1/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'admin1',
        'USER': 'postgres',
        'PASSWORD': '123456',
        'HOST': '127.0.0.1',
        'PORT': '5432',
    }
} if not DEBUG else {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'db.sqlite3',
        'USER': '',
        'PASSWORD': '',
        'HOST': '',
        'PORT': '',
    },
}

# Password validation
# https://docs.djangoproject.com/en/3.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/3.1/topics/i18n/

LANGUAGE_CODE = 'es-AR'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.1/howto/static-files/

STATIC_URL = '/static/'

_sign("DEFAULT", moneyed.ARS, prefix='$')
_sign("DEFAULT", moneyed.USD, prefix='US$')

moneyed.add_currency('ARS', '032', 'Peso Argentino', ['ARGENTINA'])

CURRENCIES = ('ARS', 'USD')

TINYMCE_DEFAULT_CONFIG.update({
    'toolbar': 'undo redo | '
               'formatselect | '
               'bold italic underline strikethrough | '
               'fontselect fontsizeselect forecolor backcolor | '
               'alignleft aligncenter alignright alignjustify | '
               'bullist numlist outdent indent | '
               'removeformat | '
               'help',
})

# Activate Django-Heroku.
django_heroku.settings(locals())
