# Generated by Django 3.1.2 on 2020-12-08 20:19

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0004_auto_20201208_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12, verbose_name='precio pagado'),
        ),
        migrations.AlterField(
            model_name='item',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('ARS', 'Peso Argentino'), ('USD', 'US Dollar')], default='XYZ', editable=False, max_length=3),
        ),
    ]
