# Generated by Django 3.1.2 on 2020-12-08 20:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Sales', '0007_auto_20201208_1725'),
    ]

    operations = [
        migrations.AddField(
            model_name='sale',
            name='address',
            field=models.CharField(default='direccion', max_length=255, verbose_name='domicilio de entrega'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='sale',
            name='name',
            field=models.CharField(default='nombre', max_length=255, verbose_name='nombre del cliente'),
            preserve_default=False,
        ),
    ]
