# Generated by Django 3.1.2 on 2020-10-23 20:30

from decimal import Decimal
from django.db import migrations, models
import djmoney.models.fields
import djmoney.models.validators


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='hide_from_catalog',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12, validators=[djmoney.models.validators.MinMoneyValidator(Decimal('0.01'))]),
        ),
    ]
