# Generated by Django 3.1.2 on 2020-11-25 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0004_productvariantvalue'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='hide_from_catalog',
        ),
    ]
