# Generated by Django 3.1.2 on 2020-11-25 20:05

from decimal import Decimal
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields
import djmoney.models.validators
import tinymce.models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0005_remove_product_hide_from_catalog'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name': 'producto', 'verbose_name_plural': 'productos'},
        ),
        migrations.AlterModelOptions(
            name='productvariant',
            options={'verbose_name': 'variante de producto', 'verbose_name_plural': 'variantes de producto'},
        ),
        migrations.AlterModelOptions(
            name='productvariantvalue',
            options={'verbose_name': 'valor de variante de producto', 'verbose_name_plural': 'valores de variantes de producto'},
        ),
        migrations.AlterField(
            model_name='product',
            name='description',
            field=tinymce.models.HTMLField(verbose_name='descripcion larga'),
        ),
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price',
            field=djmoney.models.fields.MoneyField(decimal_places=2, max_digits=12, validators=[djmoney.models.validators.MinMoneyValidator(Decimal('0.01'))], verbose_name='precio'),
        ),
        migrations.AlterField(
            model_name='product',
            name='price_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('ARS', 'Peso Argentino'), ('USD', 'US Dollar')], default='XYZ', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='product',
            name='short_description',
            field=models.CharField(max_length=255, verbose_name='descripcion corta'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='productvariant',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variants', to='Products.product', verbose_name='producto'),
        ),
        migrations.AlterField(
            model_name='productvariantvalue',
            name='name',
            field=models.CharField(max_length=255, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='productvariantvalue',
            name='variant',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='values', to='Products.productvariant', verbose_name='variante de producto'),
        ),
    ]
