# Generated by Django 3.1.2 on 2020-11-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0007_imageproduct'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='photos',
            field=models.CharField(default=1, max_length=255, verbose_name='nombre2'),
            preserve_default=False,
        ),
    ]
