# Generated by Django 3.1.2 on 2020-11-28 22:36

import Products.models.product
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0010_auto_20201128_1849'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='productimage',
            options={'verbose_name': 'imagen del producto', 'verbose_name_plural': 'imagenes del producto'},
        ),
        migrations.RemoveField(
            model_name='productimage',
            name='name',
        ),
        migrations.AddField(
            model_name='productimage',
            name='description',
            field=models.CharField(default=1, max_length=255, verbose_name='descripcion'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(upload_to=Products.models.product.ProductImage.path_and_rename),
        ),
    ]
