# Generated by Django 3.1.2 on 2020-11-28 22:39

import Products.models.product
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0011_auto_20201128_1936'),
    ]

    operations = [
        migrations.AddField(
            model_name='productimage',
            name='externalUri',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Products.models.product.ProductImage.path_and_rename),
        ),
    ]
