# Generated by Django 3.1.2 on 2020-11-28 22:46

import Products.models.product
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0012_auto_20201128_1939'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='default',
        ),
        migrations.AlterField(
            model_name='productimage',
            name='externalUri',
            field=models.URLField(blank=True, null=True, verbose_name='Imagen externa'),
        ),
        migrations.AlterField(
            model_name='productimage',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=Products.models.product.ProductImage.path_and_rename, verbose_name='Imagen'),
        ),
    ]
