# Generated by Django 3.1.2 on 2020-11-29 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0013_auto_20201128_1946'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='name',
            field=models.CharField(max_length=100, verbose_name='nombre'),
        ),
    ]
