# Generated by Django 3.1.2 on 2020-12-02 00:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0015_auto_20201130_2107'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='productimage',
            managers=[
            ],
        ),
        migrations.AlterField(
            model_name='productimage',
            name='product',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='Products.product'),
        ),
    ]
