# Generated by Django 3.1.2 on 2020-12-05 21:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0016_auto_20201201_2155'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productimage',
            name='description',
        ),
    ]
