# Generated by Django 3.1.2 on 2020-12-13 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0018_auto_20201205_1855'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductVideo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('externalUri', models.URLField(blank=True, null=True, verbose_name='Video externo')),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='videos', to='Products.product')),
            ],
            options={
                'verbose_name': 'video del producto',
                'verbose_name_plural': 'videos del producto',
            },
        ),
    ]
