# Generated by Django 3.1.2 on 2020-12-20 19:30

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0023_auto_20201220_1536'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='product',
            name='unidad',
        ),
        migrations.AddField(
            model_name='product',
            name='constante',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
