# Generated by Django 3.1.2 on 2020-12-21 13:43

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0024_auto_20201220_1630'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Units',
        ),
        migrations.RemoveField(
            model_name='product',
            name='constante',
        ),
        migrations.AddField(
            model_name='product',
            name='depth_unit',
            field=models.CharField(choices=[('Metros', 'Metros'), ('Centimetros', 'Centimetros'), ('Pies', 'Pies')], default='Centimetros', max_length=100, verbose_name='unidad de la profundidad'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='height_unit',
            field=models.CharField(choices=[('Metros', 'Metros'), ('Centimetros', 'Centimetros'), ('Pies', 'Pies')], default='Centimetros', max_length=100, verbose_name='unidad del alto'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='weight',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='peso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='weight_unit',
            field=models.CharField(choices=[('Kilogramos', 'Kilogramos'), ('Gramos', 'Gramos'), ('Libras', 'Libras')], default='Gramos', max_length=100, verbose_name='unidad del peso'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='product',
            name='width_unit',
            field=models.CharField(choices=[('Metros', 'Metros'), ('Centimetros', 'Centimetros'), ('Pies', 'Pies')], default='Centimetros', max_length=100, verbose_name='unidad del ancho'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='product',
            name='depth',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='profundidad'),
        ),
        migrations.AlterField(
            model_name='product',
            name='height',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='alto'),
        ),
        migrations.AlterField(
            model_name='product',
            name='width',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)], verbose_name='ancho'),
        ),
    ]
