# Generated by Django 3.1.2 on 2020-12-21 18:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('Products', '0026_auto_20201221_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProductRating',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.DecimalField(decimal_places=2, max_digits=3)),
                ('product', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ratings', to='Products.product')),
            ],
            options={
                'verbose_name': 'rating del producto',
                'verbose_name_plural': 'ratings del producto',
            },
        ),
    ]
